### ISSUE TITLE
Support synchronization of all CRD resources

### ISSUE THREAD

**Issue by cleverhu** [clusterpedia-io/clusterpedia#111]
### What would you like to be added?

Support synchronization of all CRD resources by a field designed in pediacluster.

### Why is this needed?

It is useful for front-end display and viewing of all CRD resources.

**Comment by Iceber** [comment]
It seems to be quite useful, after all, custom resources are more dynamic and it would be complicated for users to configure them in pediacluster every time they install crd.

However, for synchronising uncontrollable amounts of custom resources, which can lead to many long connections, it can be used as an experimental feature.

**Comment by Iceber** [comment]
`SyncAllCustomResources` is provided as an experimental feature and needs to be turned on in feature gates - `--feature-gates AllowSyncAllCustomResources=true`

The number of `custom resource definitions` is uncontrollable and may be very large, so if you encounter any exceptions or problems while synchronizing, please provide feedback in the issue in a timely manner

**Comment by Iceber** [comment]
`SyncAllCustomResources` is provided as an experimental feature and needs to be turned on in feature gates - `--feature-gates AllowSyncAllCustomResources=true`

The number of `custom resource definitions` is uncontrollable and may be very large, so if you encounter any exceptions or problems while synchronizing, please provide feedback in the issue in a timely manner
