### ISSUE TITLE
An error in the clusterpedia docs with installation module

### ISSUE THREAD

**Issue by AJ-X** [clusterpedia-io/clusterpedia#120]
### What would you like to be added?

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/38452461/160319414-0af360c1-6e24-4679-b27f-dfcd52c24cfe.png">
The operation sequence is wrong and should be changed.

### Why is this needed?

As described above.

**Comment by Iceber** [comment]
@AJ-X Thank you very much for finding this issue！
