### ISSUE TITLE
日志最好有轮滚，避免出现把磁盘写满的情况

### ISSUE THREAD

**Issue by yank1** [clusterpedia-io/clusterpedia#13]
参考

https://github.com/clusterpedia-io/clusterpedia/blob/7e301c8ce4cf81827850ab0f58f64b0457563f76/pkg/storage/internalstorage/register.go#L87

**Comment by Iceber** [comment]
Although the `internalstorage` will only print logs of errors and Slow SQL by default, there is still a risk of oversizing the log file in some cases.
It will be added to the roadmap
