### ISSUE TITLE
指定集群名称查询报错

### ISSUE THREAD

**Issue by liuzouzou** [clusterpedia-io/clusterpedia#137]
### What happened?

[root@dce-10-6-215-215 ~]# kubectl --cluster clusterpedia get pod
CLUSTER           NAME                             READY   STATUS      RESTARTS      AGE
cluster-178-220   hello-79dbf8f975-fhkcl           1/1     Running     0             128m
cluster-example   cm-env-test-pod                  0/1     Completed   0             5d1h
cluster-example   ng1-849588dbb9-dqc7r             1/1     Running     3 (19h ago)   2d16h
cluster-178-220   nginx-f89759699-rkgkg            1/1     Running     0             130m
cluster-128-168   dao-2048-4-9cdc87d65-7hbdb       1/1     Running     7 (36d ago)   210d
cluster-128-168   dao-2048-6d6dfbb6ff-cjmps        1/1     Running     6 (36d ago)   210d
cluster-128-168   my222-dao-2048-d96b45f57-hpcgn   1/1     Running     8 (36d ago)   210d

##  指定了某个具体的集群名称提示找不到
[root@dce-10-6-215-215 ~]# kubectl --cluster cluster-128-168 get pod
error: no server found for cluster "cluster-128-168"
[root@dce-10-6-215-215 ~]#

### What did you expect to happen?

可以根据某个集群名称找到对应的 pod

##  指定了某个具体的集群名称提示找不到
[root@dce-10-6-215-215 ~]# kubectl --cluster cluster-128-168 get pod
error: no server found for cluster "cluster-128-168"

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"7c28a83e67cb506f9df948d7b23698f8f9c279b8", GitTreeState:"clean", BuildDate:"2021-07-15T08:58:53Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

**Comment by ycsk02** [comment]
Hi liuzouzou, please check the kubeconfig file ~/.kube/config, if there is a cluster named cluster-128-168. If it is not exists, please regenerate the kubeconfig for clusterpedia's cluster by the script hack/gen-clusterConfigs.sh.

**Comment by liuzouzou** [comment]
感谢，重新生成后可以了
