### ISSUE TITLE
Clusterpedia 分页的时候不能根据 namespace 进行分页

### ISSUE THREAD

**Issue by liuzouzou** [clusterpedia-io/clusterpedia#139]
## 查询 ns 的时候，限制了条数为 2，进行查询的时候，报错
[root@dce-10-6-215-215 pod-dir]# kubectl --cluster cluster-example get namespace --chunk-size 2
error: the server doesn't have a resource type "namespace"

### What did you expect to happen?

可以查询出 ns，并且返回两条数据

### How can we reproduce it (as minimally and precisely as possible)?

kubectl --cluster cluster-example get namespace --chunk-size 2

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"7c28a83e67cb506f9df948d7b23698f8f9c279b8", GitTreeState:"clean", BuildDate:"2021-07-15T08:58:53Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

**Comment by Iceber** [comment]
Are the namespace resources synchronized?
```bash
kubectl --cluster cluster-example api-resources
```

**Comment by Iceber** [comment]
@liuzouzou Does the problem still exist after namespace synchronization?

**Comment by liuzouzou** [comment]
> @liuzouzou Does the problem still exist after namespace synchronization?

No problem, thank you
