### ISSUE TITLE
clusterpedia的文档中，关于指定集群的介绍中，后面多了个双引号"

### ISSUE THREAD

**Issue by liuzouzou** [clusterpedia-io/clusterpedia#140]
### What happened?

# 指定集群也可以使用 --cluster <cluster name> 来指定
# 文档最后面多了个"
kubectl --cluster cluster-1 get deployments"

### What did you expect to happen?

修改文档，去掉"

### How can we reproduce it (as minimally and precisely as possible)?

文档地址：https://clusterpedia.io/zh-cn/docs/usage/search/multi-cluster/
 # 在指定集群的说明里面
指定集群也可以使用 --cluster <cluster name> 来指定
kubectl --cluster cluster-1 get deployments"

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

**Comment by Iceber** [comment]
It is recommended that issues for the document be submitted in https://github.com/clusterpedia-io/website.

@liuzouzou Are you interested in fixing this issue?

**Comment by liuzouzou** [comment]
> 建议文档问题提交到https://github.com/clusterpedia-io/website。
> 
> @liuzouzou你有兴趣解决这个问题吗？

I go to https://github.com/clusterpedia-io/website commit the issue and resolve it
