### ISSUE TITLE
未对接入集群信息做判断，一个集群可以重复接入

### ISSUE THREAD

**Issue by luozhengtest** [clusterpedia-io/clusterpedia#143]
### What would you like to be added?

1.使用A.yaml文件接入集群A
2.复制A.yaml文件，修改文件名和集群名为B
3.使用B.yaml文件接入集群
预期结果：提示集群已存在
实际结果：接入集群B
<img width="778" alt="image" src="https://user-images.githubusercontent.com/36952500/163914471-10bcb2b4-460c-4225-a01d-f6ab5bcd2cfa.png">

### Why is this needed?

对接入的yaml文件进行判断，若存在相同的集群接入，则接入失败，提示该集群已接入到clusterpedia

**Comment by Iceber** [comment]
@luozhengtest clusterpedia does not verify the address of the cluster, but rather identifies the cluster by name

Multiple accesses to the same cluster are human controllable and clusterpedia has no need to restrict this.

**Comment by Iceber** [comment]
When you actively import it twice, then it must mean something to you.

**Comment by luozhengtest** [comment]
多集群或多人操作时，前期出现误操作时没有保险，导致接入成功；后期发现问题后，只能通过确认配置或根据资源信息确定某个集群是否重复接入，再对比接入集群和已有集群，排查漏导入的集群工程巨大；而且同一个集群重复接入后，除了增加检索结果的冗余度，无实际意义

**Comment by Iceber** [comment]
实际上没有一个非常合适的方式来区分不同的集群，如果只是通过配置来区分的话，用户如果存在误操作依然可能会使用不同的 token 或者集群地址来接入相同的集群。

如果我们最终的目的是避免接入相同集群的话，那么并没有非常好的方案，用户总能用各种方式来接入相同集群

**Comment by luozhengtest** [comment]
好的
