### ISSUE TITLE
手动转换kubeconfig文件配置后，提示file name to long

### ISSUE THREAD

**Issue by luozhengtest** [clusterpedia-io/clusterpedia#146]
### What would you like to be added?

.kube/config文件中client证书配置为路径时，手动替换为base64形式，在接入clusterpedia时，提示“file name to long”
<img width="1411" alt="wecom-temp-50b28feccd7090c8d3d8a6d591644c7d" src="https://user-images.githubusercontent.com/36952500/164140938-73be1d93-b5b6-4f8e-ae51-e0f35f9a9817.png">

### Why is this needed?

对配置读取进行优化

**Comment by Iceber** [comment]
The base64 data should be configured in a field like `user.client-certificate-data` that ends with `data`, You should have configured it in `user.client-certificate`, which is wrong
