### ISSUE TITLE
To access the cluster using the get access to cluster ca and token method, replace the namespace in kubeconfig with default

### ISSUE THREAD

**Issue by luozhengtest** [clusterpedia-io/clusterpedia#149]
### What would you like to be added?

1.使用获取被接入集群ca和token方式接入集群
2.获取ca和token失败
<img width="1407" alt="wecom-temp-2668adfb8827eb1598677c14254ecc07" src="https://user-images.githubusercontent.com/36952500/164142641-843402d4-36d8-4847-90ab-57d225dc2b7d.png">

### Why is this needed?

将被接入集群的kubeconfig中的namespace替换为default能正常获取

**Comment by Iceber** [comment]
@luozhengtest Nice find, you can set the namespace in the command, would you be interested in modifying the documentation?

For easier viewing, can you change it to English?

**Comment by luozhengtest** [comment]
OK

**Comment by Iceber** [comment]
https://github.com/clusterpedia-io/website/pull/36
