### ISSUE TITLE
Allows resources to be synchronized using the singular/plural of the resource and can be case-insensitive

### ISSUE THREAD

**Issue by liuzouzou** [clusterpedia-io/clusterpedia#153]
### What would you like to be added?

Allows resources to be synchronized using the singular/plural of the resource and can be case-insensitive

### Why is this needed?

In kubernetes both singular and plural are available to query the data, which increases fault tolerance

**Comment by Iceber** [comment]
This is very meaningful and improves fault tolerance, Thanks!
