### ISSUE TITLE
After paging by clusterpedia, specify offset to filter by number of entries, should filter by number of pages

### ISSUE THREAD

**Issue by luozhengtest** [clusterpedia-io/clusterpedia#154]
### What would you like to be added?

1.Retrieve resources and set the number of pagination to 5 and and set offset to 0
2.set offset to 1
3.set offset to 2
Actual results：
    1.1-5 resources retrieved
    2.2-6 resources retrieved
    3.3-7 resources retrieved
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/36952500/164368191-5685978c-b2df-421e-9663-ee391fdb1a26.png">

### Why is this needed?

Expected results：
    1.1-5 resources retrieved
    2.6-10 resources retrieved
    3.11-15 resources retrieved

**Comment by Iceber** [comment]
`Offsets` provide more basic capabilities than `pages` and are more in line with the meaning of the kube API's `ListOption.Continue`

**Comment by luozhengtest** [comment]
ok
