### ISSUE TITLE
License copyright need to be updated

### ISSUE THREAD

**Issue by wilsonwu** [clusterpedia-io/clusterpedia#159]
### What would you like to be added?

I the License file, the copyright is:
Copyright [yyyy] [name of copyright owner]

suggest to change the license copyright to correct one.

### Why is this needed?

perfesional

**Comment by Iceber** [comment]
Thank you very much for the advice!

I referenced other projects, including [kubernetes](https://github.com/kubernetes/kubernetes/blob/master/LICENSE), [kubedge](https://github.com/kubeedge/kubeedge/blob/master/LICENSE), [prometheus](https://github.com/prometheus/prometheus/blob/main/LICENSE).
And found that prometheus also rolled back a similar issue：https://github.com/prometheus/prometheus/pull/456

I'm not sure what what is right either:thinking:
