### ISSUE TITLE
upgrade featuregate `PruneLastAppliedConfiguration` `PruneManagedFields` to beta in v0.0.3

### ISSUE THREAD

**Issue by calvin0327** [clusterpedia-io/clusterpedia#167]
### What would you like to be added?

 In the past few releases, both featrue `PruneLastAppliedConfiguration` and `PruneManagedFields` have been stable and mature. Will we update these featuregate in V0.0.3?

### Why is this needed?

feature upgrade

**Comment by Iceber** [comment]
These two features are available in 0.0.9-alpha, and I feel they are very useful, and can be upgraded to beta in 0.3.0, by default to True.

@ycsk02 @27149chen @wawa0210 What do you think, or will we upgrade to beta at 0.4 or higher?

**Comment by 27149chen** [comment]
It's ok to me

**Comment by wawa0210** [comment]
The default featuregate is very useful, greatly reduces storage space, and can be released as soon as possible if possible

**Comment by ycsk02** [comment]
useful featuregate, looks good.

**Comment by Iceber** [comment]
cc @calvin0327 
Please upgrade these feature gates.
