### ISSUE TITLE
Use Collection Resource to list all resources in a namespace

### ISSUE THREAD

**Issue by 27149chen** [clusterpedia-io/clusterpedia#169]
### What would you like to be added?

Use Collection Resource to list all resources in a namespace

### Why is this needed?

Use Collection Resource to list all resources in a namespace

**Comment by ycsk02** [comment]
Hi @27149chen ,  `all resources ` what is it reference to? Do you mean workloads filtered by namespace?

**Comment by Iceber** [comment]
@ycsk02 The `all resources` are all types of resources (rbac resources, nodes, workloads etc...), should be a new Collection Resource.
However, custom resources may hold multiple versions, so we may only be able to support kubernetes built-in resources

**Comment by ycsk02** [comment]
I think we could add the new Collection Resource in collectionResources map, but maybe we can only support resources filtered by namespace through API query request, rather than kubectl command.
https://github.com/clusterpedia-io/clusterpedia/blob/562f7b78450d58823c67ee2c9f6697176d617fe3/pkg/storage/internalstorage/storage.go#L129


https://github.com/clusterpedia-io/clusterpedia/blob/562f7b78450d58823c67ee2c9f6697176d617fe3/pkg/apiserver/registry/clusterpedia/collectionresources/rest.go#L86-L91

**Comment by Iceber** [comment]
**TODO in 0.3.0**: support onlyMetadata in the url query to return only metadata data

**Comment by Iceber** [comment]
Use `kubectl get collectionresources [workloads|kuberesources]` or specify query (onlyMetadata) in the url to get only the metadata

```bash
$ kubectl get collectionresources kuberesources

$ kubectl get --raw "/apis/clusterpedia.io/v1beta1/collectionresources/kuberesources?onlyMetadata=true" 
```
> kubectl specifies that fetching yaml or json will return the full resource data, `kubectl get collectionresources kuberesources -o yaml`

`collection resources` supports most of the complex search, but for the time being only supports url query does not support search label . https://clusterpedia.io/docs/usage/search/

eg.
specify a single or some namespaces
```bash
$ kubectl get --raw "/apis/clusterpedia.io/v1beta1/collectionresources/kuberesources?onlyMetadata=true&namespaces=default" 

$ kubectl get --raw "/apis/clusterpedia.io/v1beta1/collectionresources/kuberesources?onlyMetadata=true&namespaces=default,kube-system" 
```

**Comment by Iceber** [comment]
We should provide a client for collecting resources in [client-go](https://github.com/clusterpedia-io/client-go), what do you think? @calvin0327

**Comment by calvin0327** [comment]
I think so.

**Comment by Iceber** [comment]
https://github.com/clusterpedia-io/client-go/issues/37
