### ISSUE TITLE
clusterpedia list resources only return metadat 

### ISSUE THREAD

**Issue by feeltimeQ** [clusterpedia-io/clusterpedia#187]
### What would you like to be added?

One listOptions, only return matedata information .

### Why is this needed?

When I list a resource I find that it gives me the full amount of resource information. 

Example: 
<img width="1266" alt="wecom-temp-b3b1ff0e5b7e075b32846d914e6c7ed1" src="https://user-images.githubusercontent.com/52406499/169477707-34c611fa-2a00-4cdc-a424-09f14451d565.png">

But I think sometimes I don't need the full amount of resource information in a list query, just the matedata information. Is it possible to add a query option where the list query only fetches the matedata information for the resource?

**Comment by Iceber** [comment]
Very good questions.
clusterpedia supports returning only metadata，use [k8s client-go metadata client](https://github.com/kubernetes/client-go/tree/master/metadata)
