### ISSUE TITLE
The `apiservice controller` and `crd controller` of the clustersynchro will not stop when the cluster is not healthy

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#206]
### What happened?

The `apiservice controller` and `crd controller` of the clustersynchro will not stop when the cluster is not healthy.

### What did you expect to happen?

The apiservice controller and crd controller of the synchronizer can be automatically started and stopped according to the health status of the `imported cluster`

### How can we reproduce it (as minimally and precisely as possible)?

The clustersynchro manager log set to `-v 3`, you can find the informer of `crd` and `apiservices` will keep retrying the connection when the cluster is not healthy.

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
version.Info{GitVersion:"v0.3.0-6-g114b699", GitCommit:"114b6991f917fcbac0632b7d855cc3918a69d5ce", GitTreeState:"clean", BuildDate:"2022-06-06T05:22:46Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64", KubeVersion:"v1.22.4"}
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

**Comment by Iceber** [comment]
@ONE7live This bug will be fixed in 0.5.

The [dynamic discovery manager](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/synchromanager/clustersynchro/discovery), which is a combination of `crd controller` and `apiservice controller`, will be refactored to be a more generic tool.
And [ClusterImportPolicy Controller](https://github.com/clusterpedia-io/clusterpedia/blob/276cd08d549785f2a3a8e188ef3648c0fa5a8094/pkg/controller/clusterimportpolicy/clusterimportpolicy_controller.go#L445) will also use it.

**Comment by ONE7live** [comment]
Ok, thanks for your reply, I see. Is anyone currently refactoring the dynamic discovery manager? Or how is it going? I thought maybe I could try to fix this when I have time. @Iceber

**Comment by Iceber** [comment]
This is a bit complicated, and I haven't thought through how to do it.

We have added a new component [controller manager](https://github.com/clusterpedia-io/clusterpedia/tree/main/pkg/controller) and [interface to multi-cloud platform](https://clusterpedia.io/zh-cn/docs/usage/interfacing-to-multi-cloud-platforms/) feature in 0.4, there are still a lot of optimizations to be done, if you are interested, you can learn more about it.

There are some optimization items in https://github.com/clusterpedia-io/clusterpedia/issues/185#issuecomment-1180093534, and I will submit some new issues afterwards
