### ISSUE TITLE
make images just only in cache but not load into docker

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#211]
### What happened?

1. When I just want make images from make file
2. It succeed but I can not found images from `docker images`
3. And the output is `WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load`
4. Should we use --load in make images stage?

### What did you expect to happen?

when make images succeed I can found images from `docker images`

### How can we reproduce it (as minimally and precisely as possible)?

make images

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```
main
</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
none
</details>

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
This is a issue caused by the builder of buildx.

If buidler uses `docker`, then the image will be loaded into docker even if `--load` is not used. 
You can use `docker buildx ls` to list the builders：
```bash
$  docker buildx ls
NAME/NODE       DRIVER/ENDPOINT STATUS  PLATFORMS
desktop-linux   docker
  desktop-linux desktop-linux   running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
default *       docker
  default       default         running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

If it is `docker-container`, it will not have this default behavior.

**In order to load the image into docker no matter which builder we use, I think we should add --load to the `docker buildx build`**

**Comment by wuyingjun-lucky** [comment]
Yes 
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/16109961/172749812-2b9612dd-a0aa-4c78-8b82-395c7d6998ae.png">
