### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#216]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored
https://github.com/clusterpedia-io/clusterpedia/pull/215
https://github.com/clusterpedia-io/clusterpedia/pull/209
https://github.com/clusterpedia-io/clusterpedia/pull/208

### Issues involved

https://github.com/clusterpedia-io/clusterpedia/issues/211
### Others
created pr (to be reviewed):
https://github.com/clusterpedia-io/website/pull/46

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
+1, Thank you for the contributions and weclome 🎉

Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by wuyingjun-lucky** [comment]
thank you @Iceber Hope to bring more to clusterpedia

**Comment by Iceber** [comment]
@wuyingjun-lucky I believe your participation will make clusterpedia better.
