### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by cleverhu** [clusterpedia-io/clusterpedia#217]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored
https://github.com/clusterpedia-io/clusterpedia/pulls?q=author%3Acleverhu
https://github.com/clusterpedia-io/client-go/pulls?q=author%3Acleverhu
### PRs reviewed
https://github.com/clusterpedia-io/clusterpedia/pull/182
https://github.com/clusterpedia-io/clusterpedia/pull/166

**Comment by Iceber** [comment]
lgtm +1, Thank you for the contributions and weclome 🎉

Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by cleverhu** [comment]
thank you @Iceber, I have joined the organization and hope to make more contributions in the future.
