### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by hanweisen** [clusterpedia-io/clusterpedia#230]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored
#228
#225 

### Others
https://github.com/clusterpedia-io/website/pull/39

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
Although we expect members to merge at least 3 pr in the [clusterpedia-io/clusterpedia](https://github.com/clusterpedia-io/clusterpedia), it is not mandatory.
@wuyingjun-lucky and I are confident that you will have more participation in the future.

Thank you for contributing and welcome🎉!

**Comment by Iceber** [comment]
@hanweisen Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by wuyingjun-lucky** [comment]
> Although we expect members to merge at least 3 pr in the [clusterpedia-io/clusterpedia](https://github.com/clusterpedia-io/clusterpedia), it is not mandatory. @wuyingjun-lucky and I are confident that you will have more participation in the future.
> 
> Thank you for contributing and welcome🎉!

Sorry,  I make a mistake that pull request in clusterpedia-io/website is included

**Comment by Iceber** [comment]
> Sorry, I make a mistake that pull request in clusterpedia-io/website is included

It is ok, the description of the Member requirements is not very visible, and the membership requirements will be detailed in a separate markdown in the future.
