### ISSUE TITLE
Clusterpedia robot for clusterpedia repository

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#231]
### What would you like to be added?

Add clusterpedia robot to help to review code and pull request 

### Why is this needed?

Maintainer will merge the pull request after the pipeline succeed manually although maintainers and reviewers review and approve some small pull request at very early time. 
I think we can introduce robot for improving efficiency in `code review` and `merge request`

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
Yes, it is necessary. My plan is to use https://github.com/wzshiming/gh-ci-bot to implement a simple robot, what do you think?

This is a example repo: https://github.com/wzshiming/gh-ci-bot-playground

**Comment by Iceber** [comment]
But I'm a little worried about security, because we'll be handing over a very privileged token to the action to do something.

**Comment by wuyingjun-lucky** [comment]
> https://github.com/wzshiming/gh-ci-bot

It seems lack of `lgtm` command.

**Comment by wuyingjun-lucky** [comment]
> But I'm a little worried about security, because we'll be handing over a very privileged token to the action to do something.

In other words . The maintainers and reviewers invited in the future can not write the repository directly. Maybe it is more safe .

**Comment by Iceber** [comment]
@wzshiming https://github.com/wzshiming/gh-ci-bot is missing a common command `lgtm` —— add an lgtm lable.

Although `/label-lgtm` can also be used, it seems that `/lgtm` is more commonly used.

**Comment by Iceber** [comment]
> The maintainers and reviewers invited in the future can not write the repository directly. Maybe it is more safe .

Yes, we can consider doing this.

There is a security issue, the `gh-ci-bot`scripts need to be pulled from the  https://github.com/wzshiming/gh-ci-bot  to be executed ([detail](https://github.com/wzshiming/gh-ci-bot/blob/e1b7e6044baf936ffba81769b147f038cd22345d/.github/workflows/ci-bot.yml#L79)), and this can cause more serious problems if scripts in the repository are replaced with malicious scripts due to some problems.

Can we fork to clusterpedia-io, which is a repository that only the maintainer has write access to?

**Comment by wuyingjun-lucky** [comment]
> clusterpedia

Sounds good.
Actually, In our personal gitlab repo, we also have a project named gitlab-bot in our private group to do this.

**Comment by Iceber** [comment]
Your gitlab-ci seems to work fine, would you like to migrate/contribute to clusterpedia-io? We can simply compare the two tools and choose the easiest and most convenient one.

**Comment by wuyingjun-lucky** [comment]
> Your gitlab-bot seems to work fine, would you like to migrate/contribute to clusterpedia-io? We can simply compare the two tools and choose the easiest and most convenient one.

I'd like to 
But the gitlab open api is different with github 
and 
our bot is looks too simply to satisfy clusterpedia's needs
I will try to find some way in my spare time.

**Comment by Iceber** [comment]
> I will try to find some way in my spare time.

This issue is not particularly pressing and we can have more discussions :smile:

**Comment by Iceber** [comment]
@wzshiming https://github.com/wzshiming/gh-ci-bot#gh-ci-bot looks like it needs to be updated:joy:.

**Comment by wzshiming** [comment]
Updated 😃

**Comment by wuyingjun-lucky** [comment]
ping @Iceber @wzshiming  when to apply the bot to clusterpedia

**Comment by Iceber** [comment]
@wuyingjun-lucky Thank you for the follow up, We will soon add robot.

@wzshiming  will use https://github.com/wzshiming/gh-ci-bot to support the robot, thanks to the help of @wzshiming 🌹

**Comment by Iceber** [comment]
> There is a security issue, the `gh-ci-bot`scripts need to be pulled from the https://github.com/wzshiming/gh-ci-bot to be executed ([detail](https://github.com/wzshiming/gh-ci-bot/blob/e1b7e6044baf936ffba81769b147f038cd22345d/.github/workflows/ci-bot.yml#L79)), and this can cause more serious problems if scripts in the repository are replaced with malicious scripts due to some problems.
> 
> Can we fork to clusterpedia-io, which is a repository that only the maintainer has write access to?

@wzshiming gh-ci-bot has been forked to https://github.com/clusterpedia-io/gh-ci-bot.

**Comment by Iceber** [comment]
https://github.com/clusterpedia-io/clusterpedia/pull/294 adds commands for lable and cc, assign,etc...

We currently do not use automatic merging due to the small number of approvers.

**Comment by wuyingjun-lucky** [comment]
> #294 adds commands for lable and cc, assign,etc...
> 
> We currently do not use automatic merging due to the small number of approvers.

Why not ? 
If I just modify an error words.  I think you do not need to merge it until the pipeline succeed.  It can save your time.

**Comment by Iceber** [comment]
> Why not ?
If I just modify an error words. I think you do not need to merge it until the pipeline succeed. It can save your time.

Auto-merge is good for multiple reviewers and approvers to work together, but right now I'm the only approver, and the gh-ci-bot doesn't support auto-merge yet :joy:

**Comment by wuyingjun-lucky** [comment]
> > Why not ?
> > If I just modify an error words. I think you do not need to merge it until the pipeline succeed. It can save your time.
> 
> Auto-merge is good for multiple reviewers and approvers to work together, but right now I'm the only approver, and the gh-ci-bot doesn't support auto-merge yet 😂

All right. Label  `merge` can not auto-merge.  I think `auto-merge` can save your time.

**Comment by wzshiming** [comment]
https://github.com/wzshiming/gh-ci-bot/issues/14
I create an issue for this auto-merge, and I will take the time to do it later

**Comment by Iceber** [comment]
Currently I am the only reviewer, so I will review a pr several times before merging it, currently it feels better for me to merge it manually.

In the future, when there are more approvers, we can switch to automatic merging
