### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by RuliXu** [clusterpedia-io/clusterpedia#240]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored

https://github.com/clusterpedia-io/clusterpedia/pulls?q=is%3Apr+RuliXu+

### PRs reviewed

https://github.com/clusterpedia-io/clusterpedia/pull/229
### Issues involved

https://github.com/clusterpedia-io/clusterpedia/issues/116
### Others
https://github.com/clusterpedia-io/client-go/pulls?q=lily.xu

**Comment by Iceber** [comment]
+1, Thank you for the contributions and weclome 🎉

**Comment by RuliXu** [comment]
Thank you @Iceber for your guidance and help, looking forward to contributing more ; )
