### ISSUE TITLE
apiservice and clustersynchro-manager pod synchronize localtime zone

### ISSUE THREAD

**Issue by qiuming520** [clusterpedia-io/clusterpedia#247]
### What would you like to be added?

clusterpedia_apiserver_deployment.yaml and clusterpedia_clustersynchro_manager_deployment.yaml  add 
[charts/templates/apiserver-deployment.yaml](url)
[charts/templates/clustersynchro-manager-deployment.yaml](url)
[deploy/clusterpedia_apiserver_deployment.yaml](url)
[deploy/clusterpedia_clustersynchro_manager_deployment.yaml](url)

        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
      - name: timezone
        hostPath:
          path: /etc/localtime

### Why is this needed?

The default time-zone of the container is the world clock, which is the UTC time-zone, but the default time-zone of the host (China) is CST, and the difference between the two time zones is 8 hours.
The log print time is UTC time-zone
before
![图片](https://user-images.githubusercontent.com/10718885/175481886-7b8953b2-519a-4e04-ad40-85847950be53.png)
after
![图片](https://user-images.githubusercontent.com/10718885/175481731-c807447e-6be5-49bf-99b8-e187672135ed.png)

**Comment by Iceber** [comment]
It is indeed sometimes more convenient to use local time zone.

But this is not a generic behavior (most products use utc by default and do not mount local time file) and different users may have different needs, so we can't mount files directly or by default.
> Sometimes users are likely to set the time zone uniformly for pods in the cluster, instead of just setting the local time for clusterpedia
---

Of course we support users to set the local time also looks very good.

In helm, we can add a field to the values.yaml to control whether to mount the file or not.

The yaml files in the */deploy* needs to be kept simple and generic, and users can manually modify the file before using */deploy*

@wzshiming What do you think?

**Comment by wzshiming** [comment]
If want support local time in logs, I think it is necessary to change the time format to RFC3339,
Otherwise, the local time would be confusing

**Comment by Iceber** [comment]
If we want to set the local time separately for clusterpedia, then we need to show the current time zone in the log, but unfortunately klog doesn't seem to have a way to configure the time format.

This makes it difficult to determine the time zone without looking at the pod yaml. When troubleshooting issues with other project(kube-apiserver) logs, it's easy to get confused about time zones.

Although this is an easy feature for clusterpedia to implement, we recommend a uniform approach to setting the time zone for all pods.
`PodPreset` is a good feature, but it is removed https://github.com/kubernetes/kubernetes/issues/93900，
Now you can use `Mutation Webhook` to do this. 
> Using https://github.com/redhat-cop/podpreset-webhook or https://github.com/kyverno/kyverno seems to work

I'm not sure if we want to support this in clusterpedia, I'd like to hear more

**Comment by qiuming520** [comment]
yeah ! I get you !  I will take your suggestion that The uniform approach to setting the time zone for all pods in my project. 
Of course, I will close this issue without other discussion
