### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by qiuming520** [clusterpedia-io/clusterpedia#256]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored

https://github.com/clusterpedia-io/clusterpedia/pull/235
https://github.com/clusterpedia-io/clusterpedia/pull/239
https://github.com/clusterpedia-io/clusterpedia/pull/244
### Issues involved

https://github.com/clusterpedia-io/clusterpedia/issues/247

**Comment by Iceber** [comment]
+1, Thank you for the contributions and weclome 🎉

**Comment by Iceber** [comment]
@qiuming520 Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by qiuming520** [comment]
Thank you @Iceber  for your guidance and help, looking forward to contributing more ; )
