### ISSUE TITLE
clusterpedia 后期 会不会添加一些 公有的适合复杂查询的http接口？

### ISSUE THREAD

**Issue by huoyinghao** [clusterpedia-io/clusterpedia#258]
##### 例如  

通过一个post接口 去查询 某一个集群或者多个集群的 workload(包括deploy，statefulset，job 等资源)

把这些类型以一个下面的形式返回

```json
{
    "message":"",
    "data":{
        "deploy":[],
        "statefulset":[],
        "job":[],
    }
}    
```

再进一步 可以尝试加入labelselect

#### 在以下场景可能会用得到

- 页面 需要展示拥有某一个标签的所有资源？
- 页面 需要展示 某一个集群,某一个命名空间下的一个实例 (例如某一个服务 包含deploy，statefulset，replicate，pod ) ，的所有资源
- 其他的一些奇葩需求

**Comment by Iceber** [comment]
collection resources + raw sql 不能满足需求吗

**Comment by calvin0327** [comment]
https://github.com/clusterpedia-io/client-go/pull/43

@huoyinghao 可以使用 client-go 去查询

**Comment by Iceber** [comment]
Any collection resource can meet more flexible resource combinations, and in the future there will also be the ability to customize the collection resource
