### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by duanmengkk** [clusterpedia-io/clusterpedia#282]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored
https://github.com/clusterpedia-io/clusterpedia/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed

**Comment by duanmengkk** [comment]
@Iceber

**Comment by Iceber** [comment]
+1, Thank you for the contributions and weclome 🎉

@duanmengkk Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by duanmengkk** [comment]
thank you @Iceber Hope to bring more to clusterpedia
