### ISSUE TITLE
Providing elasticsearch to choose as a storage component for user

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#286]
### What would you like to be added?

Providing elasticsearch  for user to choose as a storage component

### Why is this needed?

ES is a widely used searching engine and may help to bring more features in clusterpedia

**Comment by Iceber** [comment]
The addition of the new storage component will give clusterpedia new ideas, thank you! @wuyingjun-lucky @hanweisen
