### ISSUE TITLE
CI conflict with code 

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#306]
### What happened?

1· pipeline workflow always download golangci-lint@1.46.2
2. ci staticcheck error with not changed code  `pkg/storage/internalstorage/config.go#L8`

### What did you expect to happen?

pipeline succeed

### How can we reproduce it (as minimally and precisely as possible)?

as `what happened`

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
# paste output here

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
> 2. ci staticcheck error with not changed code pkg/storage/internalstorage/config.go#L8

It will check all the code, but the version hasn't been modified, and the problem wasn't reported before, which is a strange behavior

It looks like updating the package dependencies would be fine, would you like to do it?

> 1· pipeline workflow always download golangci-lint@1.46.2

It doesn't look like caching is being used? I still need to take a look

**Comment by wuyingjun-lucky** [comment]
> > 2. ci staticcheck error with not changed code pkg/storage/internalstorage/config.go#L8
> 
> It will check all the code, but the version hasn't been modified, and the problem wasn't reported before, which is a strange behavior
> 
> It looks like updating the package dependencies would be fine, would you like to fix it?
> 
> > 1· pipeline workflow always download golangci-lint@1.46.2
> 
> It doesn't look like caching is being used, I still need to take a look

I can fix it tomorrow and I want have a test before commit the code.  Can you wait for it ?

**Comment by Iceber** [comment]
> I can fix it tomorrow and I want to have a test before commit the code. Can you wait for it ?

It's okay.
