### ISSUE TITLE
Apiserver address is null when pediacluster is applied by kubeconfig

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#309]
### What would you like to be added?

Apiserver always be the real address.

### Why is this needed?

1、apiserver set to “”
<img width="627" alt="image" src="https://user-images.githubusercontent.com/16109961/183835433-408c9c21-e7e3-401a-8202-76ec9e3e04e9.png">

2、apiserver set to “dddd”
<img width="674" alt="image" src="https://user-images.githubusercontent.com/16109961/183835459-e3a5770b-a2f5-4b78-ad8d-4191693f7669.png">

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
Did you change the apiserver from the correct one to the wrong one?

> apiserver set to “dddd”

The conditoins and printer column were changed in v0.4.1, it will make the output look better, you can update the image version and crd yaml.

Also the string may be a domain name, maybe it doesn't work now, but it may work in the future, so we will allow the user to set any value, but if there is an exception, we will tell the user via conditons

> apiserver set to “”

The apiserver is allowed to be empty because the user can just provide kubeconfig. 
since we don't provide a multation webhook to parse the kubeconfig, the apiserver will be empty.
> Here are some discussions in https://github.com/clusterpedia-io/clusterpedia/pull/115#discussion_r828847480

**Comment by wuyingjun-lucky** [comment]
> #115 (comment)

What I am confused about is why don`t we set the apiserver to the real address during reconcile cluster

**Comment by Iceber** [comment]
> > #115 (comment)
> 
> What I am confused about is why don`t we set the apiserver to the real address during reconcile cluster

Extracting the apiserver address from kubeconfig seems like a good way to let the mutation webhook do the work. 
Try to only update the status when reconciling the cluster.

But we don't have a mutation webhook yet, so if it feels important to not have an `spec.apiserver` fields, we can check and set this field when reconciling the cluster.
> Add a mutation webhook for spec.apiserver, I'm not sure it's necessary

**Comment by wuyingjun-lucky** [comment]
> But we don't have a mutation webhook yet, so if it feels important to not have an `spec.apiserver` fields, we can check and set this field when reconciling the cluster.
> 
> >

I think you are right, let webhook do the work is more appropriately.

May be we need a clusterpedia-ctl which can fix it easily.

**Comment by Iceber** [comment]
I found https://github.com/c-bata/go-prompt and may consider using it to create a kubectl plugin in the future.

This also means that the user does not need to execute the [script](https://github.com/clusterpedia-io/clusterpedia/blob/main/hack/gen-clusterconfigs.sh) to generate cluster shortcut for kubectl

**Comment by wuyingjun-lucky** [comment]
> > > #115 (comment)
> > 
> > 
> > What I am confused about is why don`t we set the apiserver to the real address during reconcile cluster
> 
> Extracting the apiserver address from kubeconfig seems like a good way to let the mutation webhook do the work. Try to only update the status when reconciling the cluster.
> 
> But we don't have a mutation webhook yet, so if it feels important to not have an `spec.apiserver` fields, we can check and set this field when reconciling the cluster.
> 
> > Add a mutation webhook for spec.apiserver, I'm not sure it's necessary

How about to place a field named `apiserver` to pediacluster.status and we can reconcile the `apiserver` just like reconile the `Version`

**Comment by wuyingjun-lucky** [comment]
@Iceber

**Comment by Iceber** [comment]
Until we support webhook, I think this is a good way to make sure the apiserver is displayed.
