### ISSUE TITLE
Support to create database when an existing storage component is used

### ISSUE THREAD

**Issue by 27149chen** [clusterpedia-io/clusterpedia#326]
### What would you like to be added?

Support to create database when an existing storage component is used

### Why is this needed?

clusterpedia may work together with other system which already has a storage component, to better share this component, clusterpedia should support to create batabase wth the permission of the user

**Comment by Iceber** [comment]
We can add a flag to values, such as createDatabase, which defaults to false and needs to be actively set to true by the user to create the database, to ensure that the user is explicitly aware that a high privilege operation is being performed

`createDatabase=true` will render an init container for creating the database into the deployment.
