### ISSUE TITLE
the log config param `level` in helm chart is wrong

### ISSUE THREAD

**Issue by cleverhu** [clusterpedia-io/clusterpedia#331]
### What happened?

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/51436614/187180031-2550863d-7888-48bc-a44d-2a4809cbea22.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/51436614/187180200-2d34f2d4-66a8-4e67-8a7d-2dda0124ec0c.png">
When I debugged clusterpedia locally, I found that "3" passed in by level could not make clusterpedia start normally.
And it is wrong in the `charts/clusterpedia/values.yaml` file which results in it will not work properly if opened.

### What did you expect to happen?

The  log config param `level` should be fixed to the correct available value.

### How can we reproduce it (as minimally and precisely as possible)?

Install by helm chart and set the `log.enabled=true` in the `charts/clusterpedia/values.yaml`

### Clusterpedia Version

<details>

```console
# replace the pod name of clusterpedia apiserver
$ kubectl -n clusterpedia-system exec {clusterpedia-apiserver-pod-name} -- apiserver --version=raw
version.Info{GitVersion:"v0.4.1", GitCommit:"d1652e852b5c1f102b8a69c6b176f9055a502e1c", GitTreeState:"clean", BuildDate:"2022-08-04T05:41:46Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64", KubeVersion:"v1.24.1"}

# replace the pod name of clusterpedia clustersynchro-manager
$ kubectl -n clusterpedia-system exec {clustersynchro-manager-pod-name} -- clustersynchro-manager --version=raw
# paste output here
```

</details>

### Host Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

**Comment by cleverhu** [comment]
log level must be one of [Silent, Error, Warn, Info], Default should be is 'Warn'.

**Comment by Iceber** [comment]
@ONE7live hi, if you have any problems with this issue, we can discuss it together.

**Comment by ONE7live** [comment]
> @ONE7live hi, if you have any problems with this issue, we can discuss it together.

@Iceber Sorry, the daily work is a bit busy. Just submitted a PR( #346 ) on this issue, please review
