### ISSUE TITLE
Mark pediacluster status.Version as optional field.

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#333]
### What would you like to be added?

Mark pediacluster status.Version as optional field. See as https://github.com/clusterpedia-io/clusterpedia/pull/328

### Why is this needed?
[Version](https://github.com/clusterpedia-io/clusterpedia/blob/main/staging/src/github.com/clusterpedia-io/api/cluster/v1alpha2/types.go#:~:text=json%3A%22apiserver%2Comitempty%22%60-,//%20%2Brequired,Version%20string%20%60json%3A%22version%2Comitempty%22%60,-//%20%2Boptional)
 ```

	// +required
	// +kubebuilder:validation:Required
	Version string `json:"version,omitempty"`

 ```
    

The `Version` can not mark as `required` field with  `omitempty` tag otherwise it can not generate a required field in CRD

**Comment by wzshiming** [comment]
Testing robot, please ignore

/unassign KUANG-CHENG

**Comment by wzshiming** [comment]
Testing robot, please ignore

/assign KUANG-CHENG

**Comment by wuyingjun-lucky** [comment]
> Testing robot, please ignore
> 
> /assign KUANG-CHENG

@wzshiming @Iceber  
Hi 
Can we modify the robot name like `clusterpedia-bot` or `cp-bot`

**Comment by wzshiming** [comment]
> > Testing robot, please ignore
> > /assign KUANG-CHENG
> 
> @wzshiming @Iceber Hi Can we modify the robot name like `clusterpedia-bot` or `cp-bot`

Of course, register a GitHub account with the desired name, and configure its TOKEN here
https://github.com/clusterpedia-io/clusterpedia/blob/d68e6d43f1f7795899329dff177064cc5b2dc00c/.github/workflows/bot.yml#L65

**Comment by Iceber** [comment]
> Of course, register a GitHub account with the desired name, and configure its TOKEN here

This requires a separate account or a separate server to run the github apps.
But the api limitations of a separate normal account are greater than github action, and we don't have our own separate server yet.

@wuyingjun-lucky We could support this in the future, which is a good idea.

**Comment by wuyingjun-lucky** [comment]
@KUANG-CHENG  you can go on with this job

**Comment by Iceber** [comment]
@KUANG-CHENG Hi, if you have any questions, we can discuss together.

**Comment by KUANG-CHENG** [comment]
I'm sorry I haven't submitted it so late. I've done the issue and when the mailbox comes down, I'll submit it in about three or four days as soon as possible. @Iceber

**Comment by Iceber** [comment]
@KUANG-CHENG HI, This issue has been fixed.
If you're interested, we have a good first issue https://github.com/clusterpedia-io/clusterpedia/issues/365 to fix, and your contributions are welcome!
