### ISSUE TITLE
Change the name of the ci robot to clusterpedia-bot

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#337]
### What would you like to be added?

https://github.com/clusterpedia-io/clusterpedia/issues/333#issuecomment-1234049023

- [x] the clusterpedia-bot account is created @clusterpedia-bot.
- [x] configure the secret key of the ci bot https://github.com/clusterpedia-io/clusterpedia/issues/333#issuecomment-1234052674

@wuyingjun-lucky @wzshiming We will track and test the new bot in this

### Why is this needed?

The name of the ci robot uses `clusterpedia-bot` to replace `github-actions` is more reasonable

**Comment by wuyingjun-lucky** [comment]
looks pretty

**Comment by Iceber** [comment]
Looks like it's working well 🎉
