### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by wuyingjun-lucky** [clusterpedia-io/clusterpedia#379]
Sponsoring @xyz2277  to be a Member of Clusterpedia Community.

### PRs authored
core-author of feature memory-storage
https://github.com/clusterpedia-io/clusterpedia/pull/345

**Comment by Iceber** [comment]
+1, @xyz2277 Thanks for your contribution in the memory storage

**Comment by Iceber** [comment]
@xyz2277 Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by xyz2277** [comment]
> @xyz2277 Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

Done~
