### ISSUE TITLE
provide a clusterpedia client to make it easier to use

### ISSUE THREAD

**Issue by calvin0327** [clusterpedia-io/clusterpedia#45]
1. `Clusterpedia` uses `LabelSelector` to filter data, but you need to manually build the `Options` object
2. We need to use a more native way to call, like `client-Go`
3. You only need to provide a`kubeconfig` to get the clientset of client-go

Here's a [project](https://github.com/calvin0327/clusterpedia-client) to solve the above problem.

Welcome to discuss it here👏

**Comment by Iceber** [comment]
repo: https://github.com/clusterpedia-io/client-go
