### ISSUE TITLE
make synchromanager worker configurable

### ISSUE THREAD

**Issue by cleverhu** [clusterpedia-io/clusterpedia#458]
### What would you like to be added?

1. Add option WorkerNumber  for `clustersynchro-manager` such as 
```
WorkerNumber int          // WorkerNumber is the number of worker goroutines
```
2. change the code from `synchromanager.Run(1, ctx.Done())` to `synchromanager.Run(c.WorkerNumber, ctx.Done())` in 
`pkg/synchromanager/clustersynchro_manager.go`
3. If the WorkerNumber is less than or equal to 0, we should set the default value to 3.

### Why is this needed?

Now  the worker goroutine number for the cluster synchronization controller in clustersynchro manager is hardcode to 1, which results in the cluster init will become slowly if the user joined too many clusters. Therefore, the worker goroutine number should be configurable.

**Comment by Iceber** [comment]
@wlp1153468871 If there are any questions we can discuss together.

**Comment by wlp1153468871** [comment]
> @wlp1153468871 If there are any questions we can discuss together.

I'm a bit busy recently, I'll deal with it on weekends.Thanks.
