### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by ONE7live** [clusterpedia-io/clusterpedia#466]
I'm requesting to be a Member of Clusterpedia Community.

### PRs authored

https://github.com/clusterpedia-io/clusterpedia/pulls?q=is%3Apr+ONE7live+

**Comment by wuyingjun-lucky** [comment]
+1 from me

**Comment by Iceber** [comment]
+1 @ONE7live Thanks for your contribution

Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by ONE7live** [comment]
Thanks @Iceber @wuyingjun-lucky, looking forward to contributing more in the future.
