### ISSUE TITLE
Support for searching resources by owner

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#49]
It is difficult to search for resources by their owner relationships in `kubernetes`.
**`clusterpedia` will first introduce this experimental feature in `internalstorage`**.

There are two types of owner functions.
- [x] Query based on the owner's UID
- [ ] Query by owner's name, and support for setting the owner's GVR

In addition, owner filtering supports the ability to raise the seniority to meet the function of ancestor query.

---

Based on the above features, we plan to add four labels to the internalstorage first:
* `internalstorage.clusterpedia.io/owner-uid`
* `internalstorage.clusterpedia.io/owner-name`
* `internalstorage.clusterpedia.io/owner-gvr`
* `internalstorage.clusterpedia.io/owner-seniority`
> **Experimental function, the url query is not available for now**

### internalstorage search and sql examples
**search pods base on the UID of the owner**, label selector is 
`internalstorage.clusterpedia.io/owner-uid=018442f8-8e14-11eb-9f9e-0242ac130002`
```sql
SELECT * FROM `resources` WHERE `group` = "" AND `version` = "v1" AND `resource` = "pods" AND `cluster` = "cluster-dce3" AND \
    owner_uid  = "018442f8-8e14-11eb-9f9e-0242ac130002"
```

**search pods based on the UID of the grandfather owner**, label selector is 
`internalstorage.clusterpedia.io/owner-uid=018442f8-8e14-11eb-9f9e-0242ac130002,internalstorage.clusterpedia.io/owner-seniority=1`
```sql
SELECT * FROM `resources` WHERE `group` = "" AND `version` = "v1" AND `resource` = "pods" AND `cluster` = "cluster-dce3" AND \
        owner_uid IN (SELECT `uid` FROM `resources` WHERE `cluster` = "cluster-dce3" AND owner_uid = "018442f8-8e14-11eb-9f9e-0242ac130002")
```

An owning object must be in the same namespace as the dependent, or be cluster-scoped.
**search pods based on the name of the grandfather owner**, label selecttor is 
`internalstorage.clusterpedia.io/owner-name=dmp-eureka-enhance-1,internalstorage.clusterpedia.io/owner-seniority=1`
```sql
SELECT * FROM `resources` WHERE `group` = "" AND `version` = "v1" AND `resource` = "pods" AND `cluster` = "cluster-dce3" AND \
    owner_uid IN (SELECT `uid` FROM `resources` WHERE `cluster` = "cluster-dce3" AND \
        owner_uid IN (SELECT `uid` FROM `resources` WHERE `cluster` = "cluster-dce3" AND `name` = "dmp-eureka-enhance-1" AND `namespace` = "dmp"))
```

**Comment by panpan0000** [comment]
it will be useful to query pods belonging to a rs/deployment  :+1

**Comment by wawa0210** [comment]
This scene is very useful, In the real scene, we can directly find its associated pods through deployment

**Comment by Iceber** [comment]
Now supports querying by `owner-uid` https://github.com/clusterpedia-io/clusterpedia/pull/50，
 `owner-key` still needs to be discussed
