### ISSUE TITLE
Add automatic cleaning mechanism

### ISSUE THREAD

**Issue by yanrongshi** [clusterpedia-io/clusterpedia#511]
### What would you like to be added?

clusterpedia synchronizes periodic data cleansing mechanisms,Preferably, the automatic cleaning mechanism can be turned on or off, as well as custom times

### Why is this needed?

After I removed the cluster from the platform, I was still able to search and see the namespace information associated with the cluster,This seems unreasonable

**Comment by Iceber** [comment]
@yanrongshi If you remove the cluster by deleting pediacluster resources normally, there will be no garbage data in storage.

If there is garbage data, then you must have skipped the cluster cleanup by removing the finalizer, which is not recommended in any controller
