### ISSUE TITLE
Propose to provide live playground in killercoda

### ISSUE THREAD

**Issue by panpan0000** [clusterpedia-io/clusterpedia#522]
### What would you like to be added?

on https://killercoda.com/ 

### Why is this needed?

live demo

**Comment by Iceber** [comment]
This is a very useful proposal, Thanks!

**Comment by Iceber** [comment]
@calvin0327 has built the clusterpedia playground
https://killercoda.com/clusterpedia

repo: https://github.com/clusterpedia-io/killercoda
