### ISSUE TITLE
[MEMBERSHIP REQUEST] New Member of Clusterpedia

### ISSUE THREAD

**Issue by khareyash05** [clusterpedia-io/clusterpedia#562]
I'm requesting to be a Member of Clusterpedia Community.

**Comment by Iceber** [comment]
+1  :partying_face: 
Thank you very much for your contribution to provide clusterpedia with installation via kustomize and for adding a lot of tests!

**Comment by khareyash05** [comment]
Thank you @Iceber. Will continue to add a significant impact to Clusterpedia

**Comment by Iceber** [comment]
@khareyash05 Invited, please visit https://github.com/clusterpedia-io to accept the invitation.

**Comment by khareyash05** [comment]
Done Thank you
