### ISSUE TITLE
support discovery of abnormal states during resource synchronization

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#6]
During resource synchronization, the `informer reflector` cannot report errors externally if a resource(custom resource) is deleted, or after not having the correct resource permissions.

We need to make the `reflector` able to tell the `resource synchro` more information

**Comment by ycsk02** [comment]
Abnormal resource synchronization information can be displayed in SyncResources of cluster status
SharedIndexInformer supports setting a custom error handling function by the Config item WatchErrorHandler.  
Add WatchErrorHandler in the resourceVersionInformer to specify the custom error handler. Due to reflector's watchErrorHandler is a unexported field, it requires a custom reflector.  


```
func ErrorHandlerForResourceSynchro(synchro *ResourceSynchro) informer.WatchErrorHandler {
	return func(_ *informer.Reflector, err error) {
		status := clusterv1alpha2.ClusterResourceSyncCondition{
			Status:             clusterv1alpha2.SyncStatusError,
			Reason:             err.Error(),
			LastTransitionTime: metav1.Now().Rfc3339Copy(),
		}
		synchro.status.Store(status)
	}
}

	informer.NewResourceVersionInformer(
		synchro.cluster,
		synchro.listerWatcher,
		synchro.cache,
		synchro.example,
		synchro,
	).SetWatchErrorHandler(ErrorHandlerForResourceSynchro(synchro)).Run(informerStopCh)

	config := &Config{
		ListerWatcher: lw,
		ObjectType:    exampleObject,
		RetryOnError:  false,
		Process: func(obj interface{}) error {
			deltas := obj.(cache.Deltas)
			return informer.HandleDeltas(deltas)
		},
		Queue: cache.NewDeltaFIFOWithOptions(cache.DeltaFIFOOptions{
			KeyFunction:           cache.DeletionHandlingMetaNamespaceKeyFunc,
			KnownObjects:          informer.storage,
			EmitDeltaTypeReplaced: true,
		}),
		WatchErrorHandler: informer.watchErrorHandler,
	}
```

```
  Sync Resources:
    Group:  apps
    Resources:
      deployments
    Group:
    Resources:
      pods
    Group:  iam.aiscope
    Resources:
      users
    Versions:
      v1alpha2
Status:
  Conditions:
    Last Transition Time:  2022-04-25T07:50:17Z
    Message:
    Reason:                Running
    Status:                True
    Type:                  ClusterSynchroInitialized
    Last Transition Time:  2022-04-25T07:50:17Z
    Message:
    Reason:                Healthy
    Status:                True
    Type:                  Ready
  Sync Resources:
    Group:  apps
    Resources:
      Kind:        Deployment
      Name:        deployments
      Namespaced:  true
      Sync Conditions:
        Last Transition Time:  2022-04-25T07:50:17Z
        Status:                Syncing
        Storage Version:       v1
        Version:               v1
    Group:
    Resources:
      Kind:        Pod
      Name:        pods
      Namespaced:  true
      Sync Conditions:
        Last Transition Time:  2022-04-25T07:50:17Z
        Status:                Syncing
        Storage Version:       v1
        Version:               v1
    Group:                     iam.aiscope
    Resources:
      Kind:        User
      Name:        users
      Namespaced:  false
      Sync Conditions:
        Last Transition Time:  2022-04-25T08:47:52Z
        Status:                Syncing
        Storage Version:       v1alpha2
        Version:               v1alpha2
  Version:                     v1.22.4

```

```
  Sync Resources:
    Group:  apps
    Resources:
      deployments
    Group:
    Resources:
      pods
    Group:  iam.aiscope
    Resources:
      users
    Versions:
      v1alpha2
Status:
  Conditions:
    Last Transition Time:  2022-04-25T07:50:17Z
    Message:
    Reason:                Running
    Status:                True
    Type:                  ClusterSynchroInitialized
    Last Transition Time:  2022-04-25T07:50:17Z
    Message:
    Reason:                Healthy
    Status:                True
    Type:                  Ready
  Sync Resources:
    Group:  apps
    Resources:
      Kind:        Deployment
      Name:        deployments
      Namespaced:  true
      Sync Conditions:
        Last Transition Time:  2022-04-25T07:50:17Z
        Status:                Syncing
        Storage Version:       v1
        Version:               v1
    Group:
    Resources:
      Kind:        Pod
      Name:        pods
      Namespaced:  true
      Sync Conditions:
        Last Transition Time:  2022-04-25T07:50:17Z
        Status:                Syncing
        Storage Version:       v1
        Version:               v1
    Group:                     iam.aiscope
    Resources:
      Kind:
      Name:        users
      Namespaced:  false
      Sync Conditions:
        Last Transition Time:  2022-04-25T08:52:49Z
        Message:               cluster not supported resource: no matches for iam.aiscope/, Resource=users
        Reason:                SynchroCreatingFailed
        Status:                Unknown
        Version:
  Version:                     v1.22.4

```

**Comment by ycsk02** [comment]
When reconciling PediaCluster, only in the clustersynchro.New assignment resourceNegotiator, so resourceNegotiator.restmapper is unaware of the resources changes in Kubernetes. we could retrieve the Mapper in setSyncResources.

[https://github.com/clusterpedia-io/clusterpedia/blob/ce5218f19b5aa21157244daddf504e1a87f73d81/pkg/synchromanager/clustersynchro_manager.go#L256-L266](url)

When the synchronized resource configuration in PediaCluster has not been modified, but the user deleted the corresponding resource in Kubernetes, we update the SyncConditions for the resource in PediaCluster Status instead of deleting it. 

[https://github.com/clusterpedia-io/clusterpedia/blob/main/pkg/synchromanager/clustersynchro/cluster_synchro.go#L366-L368](url)

And reflector.watchErrorHandler starts with lower case, is not exposed for external use.

@Iceber Do you have any suggestions?

**Comment by Iceber** [comment]
The restmapper is actually only used for geting internal resources, while the custom resource controller will reconcile the custom resource information.

If the actual internal version or resources change due to cluster upgrade, I think the monitor can trigger the restmapper update, after all, the version will be checked in the monitor, of course, now only when the cluster is restored after losing connection will the version check be triggered, but we can consider optimizing it to periodic version check, so that If the cluster is upgraded without interrupting the service, the version update can still be checked.

In addition, rebuilding the restmapper is actually a rather costly method, and it may not be friendly to perform this step every time in syncResource

Also for restmapper, we can consider working with resource error checking, when a resource is not found, it could be a change in resources within the cluster (e.g. some resources are disabled via kube apiserver), which need to trigger a rebuild of restmapper and syncResources

**Comment by Iceber** [comment]
> And reflector.watchErrorHandler starts with lower case, is not exposed for external use.

The reason I'm not a big fan of copying reflector.go is that we don't need to modify reflector.go for a while, and copying it introduces additional maintenance costs and risk of errors.

If we are just using reflection, then we actually just need to keep it the same way as cache.Controller (e.g. by stating in a comment that it needs to be consistent with that part of the code)

I think it is not necessary to follow the rules in some functions, but rather to use the best and lowest cost way.

Of course, if we have to modify the reflector for some reason, then we copy and modify it
