### ISSUE TITLE
Support for cluster authentication via kubeconfig

### ISSUE THREAD

**Issue by Iceber** [clusterpedia-io/clusterpedia#95]
### What would you like to be added?

Use kubeconfig directly, instead of filling in ca, cert, key, etc. separately in PediaCluster

### Why is this needed?

Using kubeconfig will make the creation of pediacluster much easier.

**Comment by 27149chen** [comment]
We are investigating clusterpedia to see if it can be used in our products, but kubeconfig is a MUST to us. Could you consider to put it to v0.2.0?

**Comment by Iceber** [comment]
@27149chen Can be added to 0.2.0 if needed. 
However, in the first stage, it will support setting the data of kubeconfig directly in the PeidaCluster resource, instead of referencing the data in other resources (such as configmap, secret). Does this meet your needs?

**Comment by 27149chen** [comment]
yes, it is acceptable for the first stage
